---
- name: Preflight checks
  hosts: localhost
  gather_facts: false
  roles:
    - preflight

- name: Bootstrap server
  hosts: servers
  remote_user: root
  gather_facts: true
  roles:
    - base # Install and configure fundamental packages
    - user # Set up a normal user to use the rest of the way

- name: Configure server
  hosts: servers
  remote_user: jpnance
  gather_facts: false
  roles:
    - docker # Install and configure Docker for use
    - chezmoi # Install and configure chezmoi for use
    - apps # Clone apps, install dependencies, and start Docker containers
    - certs # Copy existing SSL certificates from outgoing server and install certbot
    - nginx # Install nginx and set up virtual hosts for apps
    - cleanup # Remove private key and special SSH configuration
